🧪 test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,5 +1,5 @@
 
-name: test
+name: MyWorkflow
 
 on:
   push:
@@ -26,28 +26,37 @@ jobs:
         uses: actions/checkout@v4
       - name: Detect package manager
         id: detect-package-manager
-        run: if [ -f "${{ github.workspace }}/yarn.lock" ]; then echo "manager=yarn"
-          >> $GITHUB_OUTPUT  echo "command=install" >> $GITHUB_OUTPUT  echo "runner=yarn"
-          >> $GITHUB_OUTPUT echo "lockfile=yarn.lock" >> $GITHUB_OUTPUT exit 0 elif
-          [ -f "${{ github.workspace }}/package.json" ]; then echo "manager=npm" >>
-          $GITHUB_OUTPUT echo "command=ci" >> $GITHUB_OUTPUT echo "runner=npx --no-install"
-          >> $GITHUB_OUTPUT echo "lockfile=package-lock.json" >> $GITHUB_OUTPUT exit
-          0 else echo "Unable to determine package manager" exit 1 fi
+        run: "|\n                if [ -f \"${{ github.workspace }}/yarn.lock\" ];
+          then\n                    echo \"manager=yarn\" >> $GITHUB_OUTPUT\n    \
+          \                echo \"command=install\" >> $GITHUB_OUTPUT\n          \
+          \          echo \"runner=yarn\" >> $GITHUB_OUTPUT\n                    echo
+          \"lockfile=yarn.lock\" >> $GITHUB_OUTPUT\n                    exit 0\n \
+          \               elif [ -f \"${{ github.workspace }}/package.json\" ]; then\n\
+          \                    echo \"manager=npm\" >> $GITHUB_OUTPUT\n          \
+          \          echo \"command=ci\" >> $GITHUB_OUTPUT\n                    echo
+          \"runner=npx --no-install\" >> $GITHUB_OUTPUT\n                    echo
+          \"lockfile=package-lock.json\" >> $GITHUB_OUTPUT\n                    exit
+          0\n                else\n                    echo \"Unable to determine
+          package manager\"\n                    exit 1\n                fi\n    \
+          \        "
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
           node-version: '20'
           cache: ${{ steps.detect-package-manager.outputs.manager }}
-          cache-dependency-path: ${{ env.BUILD_PATH }}/${{ steps.detect-package-manager.outputs.lockfile}}
+          cache-dependency-path: ${{ env.BUILD_PATH }}/${{ steps.detect-package-manager.outputs.lockfile
+            }}
       - name: Setup Pages
         id: pages
         uses: actions/configure-pages@v5
       - name: Install dependencies
-        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command}}
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command
+          }}
         working-directory: ${{ env.BUILD_PATH }}
       - name: Build with Astro
-        run: ${{ steps.detect-package-manager.outputs.runner }} astro build \ --site
-          "${{ steps.pages.outputs.origin }}" \ --base ${{ steps.pages.outputs.base_path}}
+        run: "${{ steps.detect-package-manager.outputs.runner }} astro build \\\n\
+          \                --site \"${{ steps.pages.outputs.origin }}\" \\\n     \
+          \           --base ${{ steps.pages.outputs.base_path }}"
         working-directory: ${{ env.BUILD_PATH }}
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
